### ISSUE TITLE
Selenium::WebDriver::Error::ElementClickInterceptedError

### ISSUE THREAD

**Issue by christopherpross** [miry/online_games_bots#15]
Hey,
after the exception in the login process, it runs now for some minits good.
But after a few minits, 10 or so, I get this:

```
D, [2020-02-17T12:25:28.684230 #1] DEBUG -- : : choose_building Library, University, University area
D, [2020-02-17T12:25:53.652106 #1] DEBUG -- : FAILED: Bot::LordsAndKnightsV3
D, [2020-02-17T12:25:53.687091 #1] DEBUG -- : screenshot path: "tmp/screenshot_2020-02-17-12-25-53.652.png"
D, [2020-02-17T12:25:54.987249 #1] DEBUG -- : --- Exception
D, [2020-02-17T12:25:54.987323 #1] DEBUG -- : Selenium::WebDriver::Error::ElementClickInterceptedError
D, [2020-02-17T12:25:54.987351 #1] DEBUG -- : element click intercepted: Element <button class="button button--default button-with-icon  menu-element--button--action button--action " type="button">...</button> is not clickable at point (766, 912). Other element would receive the click: <div id="over-layer--game-pending" class="in">...</div>
  (Session info: headless chrome=79.0.3945.79)
D, [2020-02-17T12:25:54.987387 #1] DEBUG -- : #0 0x5575d4d13479 <unknown>
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:371:in `click_element'
/usr/local/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/element.rb:74:in `click'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/selenium/node.rb:105:in `click'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/selenium/extensions/file_input_click_emulation.rb:6:in `click'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/selenium/nodes/chrome_node.rb:40:in `click'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/element.rb:171:in `block in click'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/element.rb:599:in `block in perform_click_action'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/base.rb:83:in `synchronize'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/element.rb:599:in `perform_click_action'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/node/element.rb:170:in `click'
/app/bot/lords_and_knights_v3.rb:105:in `block (2 levels) in research'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/result.rb:48:in `block in each'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/result.rb:45:in `loop'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/result.rb:45:in `each'
/app/bot/lords_and_knights_v3.rb:103:in `block in research'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/session.rb:345:in `within'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/dsl.rb:53:in `call'
/usr/local/lib/ruby/gems/2.7.0/gems/capybara-3.31.0/lib/capybara/dsl.rb:53:in `within'
/app/bot/lords_and_knights_v3.rb:101:in `research'
/app/bot/base.rb:44:in `block in run_commands'
/app/bot/base.rb:43:in `each'
/app/bot/base.rb:43:in `run_commands'
/app/bot/base.rb:63:in `run'
runner.rb:119:in `block in <main>'
runner.rb:92:in `each'
runner.rb:92:in `<main>'
D, [2020-02-17T12:25:54.987401 #1] DEBUG -- : ---- Console
D, [2020-02-17T12:25:54.987499 #1] DEBUG -- : ---- Body
D, [2020-02-17T12:25:54.987512 #1] DEBUG -- : -----
```

The bot restart not automatectly. I try at the moment to read in selinium to help out here...

Hopefuly this can be fixed quickly.

**Comment by miry** [comment]
@christopherpross It would great if you provide/attach to the issue the screenshot the file located in `tmp/screenshot_2020-02-17-12-25-53.652.png` ?

**Comment by miry** [comment]
I would suggest in this case increase in the condfig line `timeout: 5` to `timeout: 10`

**Comment by christopherpross** [comment]
Hey,
I will send you the screenshot per mail, because I would not post here in the ultimative public. :-) I hope this is ok.

**Comment by miry** [comment]
@christopherpross I have sent few changes. Pls try them.

**Comment by christopherpross** [comment]
Hey, yeah it is fixed now. Thank you
